;;; pimacs/doc/autoload.el -*- lexical-binding: t; -*-
;; Copyright (c) 2024, Philippe Ivaldi <www.piprime.fr>

;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;;; Code:

(defconst pim-refcard-generated-note
  "This refcard is auto-generated by [[https://github.com/pivaldi/pimacs][PIMacs]].\n"
  "Sub-title line inserted at the top of every PIMacs-generated refcard.
Edit it here; every refcard writer pulls from this constant.")

(defconst pim-refcard-section-pim
  "PIMacs Added Key Bindings"
  "Title of the section listing only `#pim'-tagged bindings.")

(defconst pim-refcard-section-default
  "Default Mode Key Bindings"
  "Title of the section dumping every binding upstream installs.")

(defun pim--linkify-docstring-symbols (str)
  "Convert curly-quoted symbol references in STR into Org `help:' links.
Each `‘NAME’' (or the ASCII fallback `\\=`NAME\\='') becomes
`[[help:NAME][NAME]]', so visiting the generated refcard inside Emacs
and pressing `C-c C-o' on a symbol pops the usual help buffer.
Captures stop at whitespace and at the closing quote, so multi-word
phrases like `‘not described’' are left as plain text."
  (replace-regexp-in-string
   "[‘`]\\([^’'`\n[:space:]]+\\)[’']"
   "[[help:\\1][\\1]]"
   str t))

(defun pim--demote-org-headings (str)
  "Return STR with every Org heading line demoted by one level.
Lines starting with one or more `*' followed by a space gain an extra
`*' so the existing sub-structure (e.g. `* Keymap =foo=' → `** Keymap
=foo='). Other lines are returned unchanged. Used to nest output from
`pim-keys-bindings-to-refcard' under an outer section heading."
  (replace-regexp-in-string "^\\(\\*+\\) " "*\\1 " str))

(defun pim--insert-split-refcard-body (keymapnames)
  "Insert two refcard sections for KEYMAPNAMES into the current buffer.
First the `#pim'-only section, then the default mode section. The two
sections are disjoint: bindings tagged `#pim' appear only in the first.
Sub-trees are demoted so the outer headings stay at level 1."
  (insert (format "\n* %s\n\n" pim-refcard-section-pim))
  (insert (pim--demote-org-headings
           (pim-keys-bindings-to-refcard keymapnames nil)))
  (insert (format "\n* %s\n\n" pim-refcard-section-default))
  (insert (pim--demote-org-headings
           (pim-keys-bindings-to-refcard keymapnames 'no-pim))))

(defun pim-format-to-title (str ext)
  "Return the formated string STR as title depending of EXT.
EXT, a string, can be org, md or txt."
  (cond
   ((equal ext "org") (format "#+title: %s" str))
   ((or (equal ext "md") (equal ext "txt")) (format "# %s" str))
   (t (error "%s is not a supported extension" ext))))

(defun pim-format-to-sub-title (str ext)
  "Return the formated string STR as sub-title depending of EXT.
EXT, a string, can be org, md or txt."
  (cond
   ((equal ext "org") (format "* %s" str))
   ((or (equal ext "md") (equal ext "txt")) (format "## %s" str))
   (t (error "%s is not a supported extension" ext))))

(defun pim-format-to-list-elem (str ext)
  "Return the formated string STR as list element depending of EXT.
EXT, a string, can be org, md or txt."
  (cond
   ((equal ext "org") (format "- %s" str))
   ((equal ext "md") (format "* %s" str))
   ((equal ext "txt") (format "• %s" str))
   (t (error "%s is not a supported extension" ext))))

(defun pim-format-to-bold (str ext)
  "Return the formated string STR in bold depending of EXT.
EXT, a string, can be org, md or txt."
  (cond
   ((or (equal ext "org") (equal ext "txt")) (format "*%s*" str))
   ((equal ext "md") (format "**%s**" str))
   (t (error "%s is not a supported extension" ext))))

(defun pim-format-to-inline-code (str ext)
  "Return the formated string STR as inline code depending of EXT.
EXT, a string, can be org, md or txt."
  (cond
   ((equal ext "org") (format "=%s=" str))
   ((equal ext "md") (format "`%s`" str))
   ((equal ext "txt") (format "\"%s\"" str))
   (t (error "%s is not a supported extension" ext))))


(defun pim-keys-bindings-to-refcard (keymaps-alist &optional mode)
  "Build an Org refcard string for the keymaps in KEYMAPS-ALIST.
KEYMAPS-ALIST is a list of (KEYMAPNAME . VALUE) entries — see
`pim-keymapname-alist' for the VALUE shape. KEYMAPNAME can carry a
prefix restriction with the form
  \"global-map::prefix:M-g a::prefix:C-c x etc…\".
If KEYMAPS-ALIST is nil, every entry in `pim-keymapname-alist' is used.

MODE selects which bindings are included:
  nil       — only bindings whose description ends in `#pim' (default).
  `no-pim'  — only bindings WITHOUT a `#pim' tag.
  t, `all'  — every binding, regardless of `#pim'."
  ;; TODO : make it interactive
  (let* ((keymap nil)
         (keymapname "")
         (keymapname-with-prefixes "")
         (mapprovider nil)
         (prefixes '())
         (prefix "")
         (result "")
         ;; Normalise MODE into the tristate `pim-which-key-get-bindings-
         ;; recursively-org' expects: nil = #pim only, t = unfiltered,
         ;; `no-pim' = non-#pim only.
         (restrict (pcase mode
                     ('nil           t)
                     ((or 't 'all)   nil)
                     ('no-pim        'no-pim)
                     (_              t))))
    (unless keymaps-alist
      (setq keymaps-alist '())
      (dolist (km pim-keymapname-alist)
        (setq keymaps-alist (append keymaps-alist (cdr km)))
        ))
    (dolist (keymap-assoc keymaps-alist)
      (setq keymapname-with-prefixes (car keymap-assoc))
      (setq prefixes (split-string keymapname-with-prefixes "::prefix:"))
      (setq keymapname (pop prefixes))
      ;; The cdr is a list `(FEATURE :KEY VALUE ...)' where FEATURE is the
      ;; (optional) feature symbol to `require' before resolving the keymap and
      ;; the plist tail carries per-keymap options. See `pim-keymapname-alist'.
      (let* ((opts (cdr keymap-assoc))
             ;; `:warmup' is a function (typically a major mode) to invoke in a
             ;; temp buffer so a keymap defined inside `define-derived-mode' or
             ;; otherwise installed lazily gets populated before enumeration.
             (warmup (plist-get (cdr opts) :warmup)))
        (setq mapprovider (car opts))
        (when mapprovider (require mapprovider))
        (when warmup
          (with-temp-buffer
            (let ((inhibit-message t))
              (ignore-errors (funcall warmup)))))
        (unless (stringp keymapname) (error "keymap name '%s' is not a string." keymapname))
        (setq keymap (symbol-value (intern keymapname)))
        (unless (keymapp keymap) (error "keymap '%s' is not a valid keymap." keymapname))
        (while ;; while loop exit cond is "prefixes nil".
            (progn
              (setq prefix (pop prefixes)) ;; prefixes decreasing.
              ;; TODO : use a temp-buffer instead !!
              (setq result (concat result (pim-which-key-get-bindings-recursively-org
                                           keymapname keymap prefix 1 nil restrict)))
              prefixes))))
    result
    ))

;;;###autoload
(defun pim-modules-key-bindings-to-refcard (modulenames fname)
  "Export the PIMacs key bindings in file (org, md and txt format supported).
MODULENAMES (list of string) is the list of PIMacs modules names that create key
bindings.
Export the refcard to FNAME.
If MODULENAMES is nil, use the variable `pim-keymapname-alist' instead."
  (interactive
   (list
    (completing-read-multiple
     "Binding module (separator regexp is %s) : "
     (append (list "All PIMacs Modules)")
             (mapcar (lambda (m) (format ":pimacs %s" (car m))) pim-keymapname-alist))
     nil t nil nil)
    (car (find-file-read-args "Export to file : " nil))))
  (let ((allkeymaps-alist '()))
    (when modulenames
      (catch 'exit
        (dolist (mname modulenames)
          (let* ((mrealname (string-trim mname ":pimacs "))
                 (keymaps-alist (cdr (assoc mrealname pim-keymapname-alist))))
            (if keymaps-alist
                (setq allkeymaps-alist (append allkeymaps-alist keymaps-alist))
              (progn
                (setq allkeymaps-alist nil)
                (throw 'exit allkeymaps-alist)))))))
    (with-temp-file fname
      (insert (pim-format-to-title
               (format
                "PIMacs/%s Key Bindings with Keyboard Option \"%s\"\n\n"
                (mapconcat 'identity modulenames ",") pim-keyboard-type) "org"))
      (insert pim-refcard-generated-note)
      (pim--insert-split-refcard-body allkeymaps-alist))))

(defun pim-keystring-kbd-consolidate (keystr)
  "Consolidate KEYSTR, a string key representation, to be read by `kbd'."
  (string-replace
   ">>" ">"
   (string-replace
    "<<" "<"
    (s-replace-regexp "\\(\[a-zA-Z0-9]\\{2,\\}\\)" "<\\1>" keystr)))
  )

(defun pim-function-check (x)
  "Test an object is a function.
Comes from https://stackoverflow.com/a/38173593"
  (if (symbolp x)
      (fboundp x)
    (functionp x)))

(defun pim-downcase-first-char (&optional string)
  "Donwcase only the first character of the input STRING."
  (when (and string (> (length string) 0))
    (let ((first-char (substring string nil 1))
          (rest-str   (substring string 1)))
      (concat (downcase first-char) rest-str))))

(defun pim-which-key-get-bindings-recursively-org (keymapname keymap prefix level &optional subkeys restrict-to-pim)
  "Returns all key bindings recursively of with prefix PREFIX with org formating.
SUBKEYS is used in recursive call to avoidd to compute previous computed keys.
RESTRICT-TO-PIM filters the emitted bindings:
  nil       — every binding (no filter).
  `no-pim'  — only bindings WITHOUT a `#pim' tag.
  any other truthy value (e.g. t) — only bindings tagged `#pim'."
  (require 'which-key)
  (require 'helpful)
  (when (not prefix) (setq prefix ""))
  (let* ((which-key-max-description-length 1000)
         (keys (if subkeys subkeys (which-key--get-bindings (kbd prefix) keymap)))
         (pim-regexp "\\(.*\\)#pim *$")
         (isPrefix (not (null keys)))
         (result "")
         (prefixf (if (equal prefix "") "" (format "Prefix =%s=" prefix)))
         (prekeymapf (if (equal prefix "") "" " on "))
         (keymapdoc (pim--linkify-docstring-symbols
                     (or (documentation-property (intern keymapname) 'variable-documentation) "")))
         (keymapf (if keymap (format "%sKeymap =%s=" prekeymapf keymapname) ""))
         (level1part ""))
    (when (and (equal prefix "") (not keymap)) (setq prefixf "No Prefix on No Keymap"))
    (setq level1part (if (or nil (eq 1 level)) (format "\n* %s%s\n%s\n\n" prefixf keymapf keymapdoc) ""))
    (and (not (listp keys)) (error "%s %s" prefix (symbol-name keymap)))
    (dolist (key keys)
      (let* ((prefixn (s-trim (format "%s %s" prefix (pim-keystring-kbd-consolidate (pop key)))))
             (sub-keys (which-key--get-bindings (kbd prefixn) keymap))
             (isSubKeyPrefix (not (null sub-keys)))
             (section-s (if isSubKeyPrefix (make-string (+ 1 level) ?*) "-"))
             (keydesc (apply #'format "%s" (cdr key)))
             (callable (and (not (string-match " " keydesc)) (pim-function-check (intern keydesc))))
             (docstring "")
             (line "")
             (separator " : "))
        (when callable
          (progn
            (setq docstring (helpful--docstring (intern keydesc) t) )
            (if docstring
                (setq docstring
                      (format " : %s"
                              (pim--linkify-docstring-symbols
                               (pim-downcase-first-char
                                (s-replace-regexp "\n.*" "" docstring)))))
              (setq docstring " (not described)"))
            (setq keydesc (format "=%s=" keydesc))
            (setq separator " calls ")))
        (setq line
              (format "%s %s=%s=%s%s%s\n"
                      section-s (if isSubKeyPrefix "Prefix " "") prefixn separator keydesc docstring))
        (when (cond
               ((null restrict-to-pim)       t)
               ((eq restrict-to-pim 'no-pim) (not (string-match-p pim-regexp line)))
               (t                            (string-match-p pim-regexp line)))
          (if (and isPrefix (not isSubKeyPrefix))
              (setq level1part (concat level1part line))
            (setq result (concat result line)))
          (when isSubKeyPrefix
            (setq
             result
             (concat
              result
              (pim-which-key-get-bindings-recursively-org
               keymapname keymap prefixn (+ 1 level) sub-keys)))))
        )
      )
    (concat level1part result)
    )
  )

;;;###autoload
(defun pim-which-key-export-bindings-recursively-to-file (keymapname keymap prefix file-name)
  "Export bindings recursively from PREFIX into file FILE-NAME with org formatting.
PREFIX should be a string suitable for `kbd'."
  ;; (interactive "sPrefix: \nF")
  (interactive (list
                (symbol-value (which-key--read-keymap))
                (read-string "Key Prefix: ")
                (car (find-file-read-args "Export to file : " nil))))
  (require 'toc-org)
  ;; (require 'help-fns)
  (let
      (
       ;; (keymapname (pim-format-to-inline-code (help-fns-find-keymap-name keymap) "org"))
       (prefixstm (if (equal prefix "")
                      ""
                    (format " Prefixed by %s" (pim-format-to-inline-code prefix "org"))))
       (title "")
       (coding-system-for-write 'utf-8-with-signature-unix))
    (with-temp-file file-name
      (point-max)
      (save-excursion
        (if (and (equal prefix "") (not keymap))
            (setq title "Key Bindings Without Prefix Nor Keymap\n\n")
          (if keymap
              (setq title
                    (format "Key Bindings of Keymap %s%s\n\n"
                            (pim-format-to-inline-code keymapname "org") prefixstm))
            (setq title (format  "Key Bindings%s Without Keymap\n\n" prefixstm))))
        (insert (pim-format-to-title title "org"))
        (insert pim-refcard-generated-note)
        (insert "* Table of Content :TOC_2:\n\n")
        (insert (pim-which-key-get-bindings-recursively-org keymapname keymap prefix 1))
        (toc-org-insert-toc)))))

;; *=================================================================*
;; *.......Functions to generate all the key bindings refcards.......*
;; *=================================================================*

;;;###autoload
(defun pim-generate-all-fundamental-key-bindings ()
  "PIMacs internal use only.
User should use `pim-which-key-export-bindings-recursively-to-file' instead."
  (let
      ((fname "")
       (prefixes pim-doc-key-binding-prefixes-to-export))
    (dolist (prefix prefixes)
      (setq fname (format "%s/doom-refcard-%s.org" (doom-module-locate-path '(:pimacs . doc)) prefix))
      (pim-which-key-export-bindings-recursively-to-file "" nil prefix fname))))

;;;###autoload
(defun pim-generate-all-keymaps ()
  "PIMacs internal use only."
  (let
      ((fname "")
       (keymaps-alist pim-doc-keymaps-to-export)
       (keymap nil)
       (keymapname "")
       (module nil))
    (dolist (kalist keymaps-alist)
      (setq keymapname (car kalist))
      (setq module (cdr kalist))
      (when module (require module))
      (setq keymap (symbol-value (intern keymapname)))
      (setq fname (format "%s/doom-refcard-%s.org" (doom-module-locate-path '(:pimacs . doc)) (s-replace-regexp "[^a-zA-Z0-1_.-]" "_" keymapname)))
      (pim-which-key-export-bindings-recursively-to-file keymapname keymap "" fname))))

;;;###autoload
(defun pim-generate-all-modules-key-bindings-refcards ()
  "PIMacs internal use only.
User should use `pim-modules-key-bindings-to-refcard' instead."
  (interactive)
  (let ((fname "")
        (keymapnames nil)
        (modulename nil)
        (module nil)
        (coding-system-for-write 'utf-8-with-signature-unix))
    (general-override-mode +1)
    (dolist (km pim-keymapname-alist)
      ;; Isolate each module so a single broken entry (missing feature, wrong
      ;; keymap variable, …) can't abort the whole batch. The failing module is
      ;; reported to *Messages* and the loop continues.
      (condition-case err
          (progn
            (setq
             modulename (car km)
             keymapnames (cdr km)
             module (intern modulename)
             fname (concat (doom-module-locate-path (cons :pimacs module))
                           (format "/%s-key-bindings-refcard.org" modulename)))
            (with-temp-file fname
              (insert (pim-format-to-title
                       (format
                        "PIMacs/%s Key Bindings with Keyboard Option \"%s\"\n\n"
                        modulename pim-keyboard-type) "org"))
              (insert pim-refcard-generated-note)
              (pim--insert-split-refcard-body keymapnames)))
        (error
         (message "[pim-refcard] skipped module %S: %s"
                  (car km) (error-message-string err)))))))

(provide 'pimacs/doc/autoload)
;;; autoload.el ends here

;; Local variables:
;; coding: utf-8
;; eval: (rename-buffer "pimacs/doc/autoload.el")
;; End:
