#+title: PIMacs/session Doom Module
Rotated backup of sessions and workspaces with auto load at startup.

* Features
- The PIMacs module ~:pimacs session~ provides regular backups of
  *your desktop and opened workspaces*, every hour by default, à la
  =destkopt-save-mode= but with rotation of five backups file. To reload a
  previous backup, use the Doom default key binding =C-c w l= and choose the
  =pim-autosave-X= or =on-shutdownX= you want.
  To reload a previous backup-ed workspace, use the PIMacs key binding =C-c w L=
  or =M-x +workspace/load=.
- It permits to automatically save and restore
  your session and workspaces using the pre-defined Doom session and workspace features.
- Finally it configures Emacs =desktop= variables ~desktop-buffers-not-to-save~
  and ~desktop-modes-not-to-save~ to be more user-friendly (do not reload help
  buffers, =.gz= files, =.gpg= files, =dired= buffers etc).

** Note

Backup concurrency is handle with a lock file inspired by =destkopt-save-mode=
so that multiple simultaneous Doom Emacs instances can not overwrite each other.


* How To Proceed With Doom Workspaces
For my part, the default Doom workspace session save-on-kill does not work
properly but with this strict process, it gives me entire satisfaction.

- Create a workspace named =test= by creating a standard workspace #x (~+workspace/new C-c w c~)
  and rename it =test= (* DON'T use ~+workspace/new-named C-c w C~ *).
- Open files in this workspace.
- Create others workspaces as needed with ~+workspace/new~.
-  Close Emacs.

When opening again Emacs, you retrieve the opened buffers in the ~test~
workspaces  with ~C-c w w~ or ~s-tab~ (~s~ mean =SUPER= key NOT =SHIFT= key)
if the module =:pimacs keys= is enabled.

* Options
- Load this module with the option ~+no-auto-save~ to disable the auto saving
  feature.
- When auto saving is enabled, setting these variables in your =config.el= file
  overwrite the default values :
  - ~pim-doom-session-auto-save-timeout~ for the auto saving
    timeout in second (default 600).
  - ~pim-doom-session-auto-save-keeped-backup-num~ for the number
    of rotated backups session (default is 5).
